//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEMATRIX.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CINEMATRIX.API.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An author patronymic required.
        /// </summary>
        public static string AuthorPatronymicRequired {
            get {
                return ResourceManager.GetString("AuthorPatronymicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An author surname required.
        /// </summary>
        public static string AuthorSurnameRequired {
            get {
                return ResourceManager.GetString("AuthorSurnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book amount pages not be less than null..
        /// </summary>
        public static string BookAmountPageNotBeLessThanNull {
            get {
                return ResourceManager.GetString("BookAmountPageNotBeLessThanNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book fund amount not be less than null..
        /// </summary>
        public static string BookFundAmountNotBeLessThanNull {
            get {
                return ResourceManager.GetString("BookFundAmountNotBeLessThanNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book fund with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string BookFundNotFound {
            get {
                return ResourceManager.GetString("BookFundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book ISBN required..
        /// </summary>
        public static string BookISBNRequired {
            get {
                return ResourceManager.GetString("BookISBNRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string BookNotFound {
            get {
                return ResourceManager.GetString("BookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book title required..
        /// </summary>
        public static string BookTitleRequired {
            get {
                return ResourceManager.GetString("BookTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book year not be less than null..
        /// </summary>
        public static string BookYearNotBeLessThanNull {
            get {
                return ResourceManager.GetString("BookYearNotBeLessThanNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A food description required..
        /// </summary>
        public static string FoodDescriptionRequired {
            get {
                return ResourceManager.GetString("FoodDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A food name required..
        /// </summary>
        public static string FoodNameRequired {
            get {
                return ResourceManager.GetString("FoodNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The food with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string FoodNotFound {
            get {
                return ResourceManager.GetString("FoodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A food price can&apos;t be less than null..
        /// </summary>
        public static string FoodPriceCanNotBeLessThanNull {
            get {
                return ResourceManager.GetString("FoodPriceCanNotBeLessThanNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A genre name required..
        /// </summary>
        public static string GenreNameRequired {
            get {
                return ResourceManager.GetString("GenreNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The genre with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string GenreNotFound {
            get {
                return ResourceManager.GetString("GenreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient or invalid data was provided for this request..
        /// </summary>
        public static string InvalidDataProvided {
            get {
                return ResourceManager.GetString("InvalidDataProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sort direction. Valid values are &apos;asc&apos; or &apos;desc&apos;..
        /// </summary>
        public static string InvalidSortDirection {
            get {
                return ResourceManager.GetString("InvalidSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A library address required..
        /// </summary>
        public static string LibraryAddressRequired {
            get {
                return ResourceManager.GetString("LibraryAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An profile date must be in range from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        public static string ProfileDateOfBirthMustBeInRange {
            get {
                return ResourceManager.GetString("ProfileDateOfBirthMustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An profile name required.
        /// </summary>
        public static string ProfileNameRequired {
            get {
                return ResourceManager.GetString("ProfileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profuke with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An profile phone number required.
        /// </summary>
        public static string ProfilePhoneNumberRequired {
            get {
                return ResourceManager.GetString("ProfilePhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An profile second name required.
        /// </summary>
        public static string ProfileSecondNameRequired {
            get {
                return ResourceManager.GetString("ProfileSecondNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A publisher name required..
        /// </summary>
        public static string PublisherNameRequired {
            get {
                return ResourceManager.GetString("PublisherNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string PublisherNotFound {
            get {
                return ResourceManager.GetString("PublisherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;{0}&apos; is required..
        /// </summary>
        public static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
    }
}
