export interface PersonCreditsDto {
  id: number,
  adult: boolean,
  backdropPath: string,
  genreIds: number[],
  originalLanguage: string,
  originalTitle: string,
  overview: string,
  popularity: number,
  posterPath: string,
  releaseDate: Date,
  title: string,
  video: boolean,
  voteAverage: number,
  voteCount: number,
  creditId: string,
  department: string,
  job: string,
  character: string,
  order: number
}
